attempt test around for ci_mac_native error
AssertionError: not(remote exception: unknown non-KJ exception of type: kj::Exception == remote exception: std::exception: block_reserved_weight (0) must be at least 2000 weight units)
https://github.com/bitcoin/bitcoin/actions/runs/22234552300/job/64322773396?pr=34422

A similar workaround may be needed for ci_mac_native_fuzz job. But the job
appears to be hung at homebrew download step witout a way to interrupt or
restart it:
https://github.com/bitcoin/bitcoin/actions/runs/22234552300/job/64322773395?pr=34422

One thing that makes the macos job different from other jobs is that it is
using capnp 1.3.0, which is newer than some other jobs. But the same error does
not occur locally with capnp 1.3.0 on nixos so it might be caused by a problem
with way capnp or bitcoin are built on macos.