ipc, moveonly: move parse address test to ipc_test.cpp
Previously ipc_test.cpp contained tests which depended on
libmultiprocess and ipc_tests.cpp contained test which didn't.
Separation was needed because libmultiprocess tests need to be build
with additional include and link paths, and cmake only has good support
for setting these on libraries not source files. The separation also
allowed the add_boost_test custom cmake function to work with no changes,
because it could find the test suite declaration in ipc_tests.cpp, and
ipc_tests.cpp would add a link-depend dependency on ipc_test.cpp and run
the other test.

But with windows support being added, the parse address test can't
easily avoid a dependecy on libmultiprocess, because it depends on the
ipc/process.h header, and ipc/process.h header will now need
platform-specific ProcessId and SocketId types defined by
libmultiprocess, rather than plain ints.

With parse address tests moved ipc_test.cpp, and there is not really a
rationale for ipc_tests.cpp to exist any more, so this change removes
it. And it moves the add_boost_test declaration so it can be used
instead of target_sources to register ipc_test.cpp with ctest.

This prevents CI errors like:

In file included from /Users/runner/work/bitcoin/bitcoin/repo_archive/src/ipc/test/ipc_tests.cpp:5:
In file included from /Users/runner/work/bitcoin/bitcoin/repo_archive/src/ipc/process.h:11:
/Users/runner/work/bitcoin/bitcoin/repo_archive/src/ipc/util.h:14:10: fatal error: 'kj/debug.h' file not found
   14 | #include <kj/debug.h>

https://github.com/bitcoin/bitcoin/actions/runs/24465865499/job/71492617687?pr=35084