cmake: Add univalue, boost, and libevent include directories
Add univalue include directory to libraries that need it it because they will
include it indirectly through setting.h files, and add libevent include
directory to libraries that need it because they will include it indirectly
through init_settings.h which includes torcontrol.h which includes
event2/util.h.

The missing cmake library dependencies trigger CI errors that may not happen on
all systems depending in how package include paths are laid out. In particular
the torcontrol / libevent errors only seem to happen on macos with homebrew.

It would probably be good to streamline headers to avoid these dependencies in
the future. It would be good if the torcontrol header did not have a pulic
dependency on libevent or, if it was just split up and the DEFAULT_TOR_CONTROL
and DEFAULT_TOR_CONTROL_PORT constants needed by init_settings.h to a different
file.

Errors look like:

D:\a\bitcoin\bitcoin\src\common\setting.h(10,1): error C1083: Cannot open include file: 'univalue.h': No such file or directory [D:\a\bitcoin\bitcoin\build\src\bitcoin.vcxproj]

In file included from /home/admin/actions-runner/_work/_temp/src/bitcoin.cpp:7:
In file included from /home/admin/actions-runner/_work/_temp/src/bitcoin_settings.h:4:
/home/admin/actions-runner/_work/_temp/src/common/setting.h:10:10: fatal error: 'univalue.h' file not found
   10 | #include <univalue.h>
      |          ^~~~~~~~~~~~
1 error generated.

D:\a\bitcoin\bitcoin\src\txmempool.h(27,1): error C1083: Cannot open include file: 'boost/multi_index/hashed_index.hpp': No such file or directory [D:\a\bitcoin\bitcoin\build\src\bitcoin.vcxproj]

In file included from /home/admin/actions-runner/_work/_temp/src/validation.h:29,
                 from /home/admin/actions-runner/_work/_temp/src/node/chainstatemanager_args.h:9,
                 from /home/admin/actions-runner/_work/_temp/src/init_settings.h:21,
                 from /home/admin/actions-runner/_work/_temp/src/bitcoin.cpp:10:
/home/admin/actions-runner/_work/_temp/src/txmempool.h:27:10: fatal error: boost/multi_index/hashed_index.hpp: No such file or directory
   27 | #include <boost/multi_index/hashed_index.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In file included from /Users/runner/work/bitcoin/bitcoin/src/qt/bitcoin.cpp:14:
In file included from /Users/runner/work/bitcoin/bitcoin/src/init_settings.h:30:
/Users/runner/work/bitcoin/bitcoin/src/torcontrol.h:14:10: fatal error: 'event2/util.h' file not found
   14 | #include <event2/util.h>
      |          ^~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

In file included from /Users/runner/work/bitcoin/bitcoin/src/test/util/setup_common.cpp:17:
In file included from /Users/runner/work/bitcoin/bitcoin/src/init_settings.h:30:
/Users/runner/work/bitcoin/bitcoin/src/torcontrol.h:14:10: fatal error: 'event2/util.h' file not found
   14 | #include <event2/util.h>
      |          ^~~~~~~~~~~~~~~
1 error generated.

In file included from /Users/runner/work/bitcoin/bitcoin/src/common/config.cpp:6:
In file included from /Users/runner/work/bitcoin/bitcoin/src/init_settings.h:30:
/Users/runner/work/bitcoin/bitcoin/src/torcontrol.h:14:10: fatal error: 'event2/util.h' file not found
   14 | #include <event2/util.h>
1 error generated.