cmake: Add bitcoin_common dependency on libevent
Prevents include errors on macos:

In file included from /Users/runner/work/bitcoin/bitcoin/src/common/config.cpp:6:
In file included from /Users/runner/work/bitcoin/bitcoin/src/init_settings.h:30:
/Users/runner/work/bitcoin/bitcoin/src/torcontrol.h:14:10: fatal error: 'event2/util.h' file not found
   14 | #include <event2/util.h>

It is difficult to avoid these errors without splitting up the torcontrol.h
file because it defines DEFAULT_TOR_CONTROL and DEFAULT_TOR_CONTROL_PORT
settings needed by init_setting.cpp but also requires libevent.

It probably would be good to split up the torcontrol.h file or avoid it having
a public dependency on libevent in the future.